config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin_role? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :diets, :eaten_products

  resources :eaten_products do
    get 'send_report', on: :member
  end

  namespace :admin do
    resources :users
  end

  root 'pages#index'
end

app/views/shared/_alerts.html.erb
<div class="container mt-3">
  <% if notice %>
    <p class="alert alert-warning" role="alert"><%= notice %></p>
  <% elsif alert %>
    <p class="alert alert-danger" role="alert"><%= alert %></p>
  <% end %>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid ms-3 me-3">

    <%= link_to 'MyDiet', root_path, class: 'navbar-brand mb-0 h1' %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <% if policy([:admin, :user]).index? %>
          <li class="nav-item">
            <%= link_to 'Users', admin_users_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <%= render 'user/session_manager' %>
      </ul>
    </div>
  </div>
</nav>