config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin_role? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :diets, :eaten_products

  resources :eaten_products do
    get 'send_report', on: :member
  end

  namespace :admin do
    resources :users
  end

  root 'pages#index'
end

app/models/diet.rb
class Diet < ApplicationRecord
  include Authorship

  belongs_to :user

  has_many :diet_meals, dependent: :destroy
  has_many :meals, through: :diet_meals

  validates :date, presence: true, uniqueness: { scope: :user_id }
  validate :date_is_in_the_past, if: :date_changed?

  scope :search_by_day, ->(date) do
    diet = Diet.find_by(date: date || Date.today)
    where(id: diet)
  end

  def format_date
    date.strftime('%d-%m-%Y')
  end

  private

  def date_is_in_the_past
    errors.add(:date, 'is in the past.') if date.present? && date < Date.today
  end
end

app/controllers/diets_controller.rb
class DietsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_diet, only: %i[show edit update destroy]
  before_action :fetch_meals, only: %i[new edit create update]
  before_action :authorize_diet!
  after_action :verify_authorized

  def index
    @diets = current_user.diets.search_by_day(params[:search_by_day])
  end

  def show; end

  def new
    @diet = current_user.diets.new
  end

  def create
    @diet = current_user.diets.build(create_diet_params)
    if @diet.save
      flash[:success] = 'Diet was successfully created!'
      redirect_to diet_path(@diet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @diet.update(update_diet_params)
      flash[:success] = 'Diet was successfully updated!'
      redirect_to diet_path(@diet)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @diet.destroy
    flash[:success] = 'Diet was successfully deleted!'

    redirect_to diets_path
  end

  private

  def create_diet_params
    params.require(:diet).permit(:name, :date, :search_by_day, meal_ids: []).merge(user: current_user)
  end

  def update_diet_params
    params.require(:diet).permit(:name, :date, :search_by_day, meal_ids: [])
  end

  def find_diet
    @diet = current_user.diets.find(params[:id])
  end

  def fetch_meals
    @meals = Meal.all
  end

  def authorize_diet!
    authorize(@diet || Diet)
  end
end

app/views/diets/_diet.html.erb
<article class="card mb-3">
    <div class="card-body">
      <h3><%= diet.name %></h3>

      <section class="card-text">
        <time datetime="<%= diet.format_date %>">
          <small>for date: <%= diet.format_date %></small>
        </time>
      </section>

      <div class="btn-group">
        <div class="left-group">
          <%= link_to 'Show', diet_path(diet), class: 'btn btn-primary mt-2 me-2'%>

          <% if policy(diet).edit? %>
            <%= link_to 'Edit', edit_diet_path(diet), class: 'btn btn-primary mt-2 me-2'%>
          <% end %>

          <% if policy(diet).destroy? %>
            <%= button_to 'Delete', diet_path(diet), method: :delete,
            form: { data: { turbo_confirm: 'Are you sure you want to delete your diet? All data will be lost.' } },
            class: 'btn btn-danger mt-2 me-2' %>
          <% end %>
        </div>
      </div>
    </div>
</article>

app/views/diets/_form.html.erb
<%= render 'shared/errors', object: @diet %>

<div class="container mt-4">

  <h2>New diet</h2>

  <%= form_with model: @diet do |f| %>

      <div class="field mt-3 col-sm-5">
        <%= f.label :name %><br />
        <%= f.text_field :name, placeholder: "Your diet", class: 'form-control' %>
      </div>

      <div class="field mt-3 col-sm-5">
        <%= f.label :date, 'For date:' %>
        <%= f.text_field :date, required: true,
          data: {
          controller: "flatpickr",
          min_date: Time.now
        } %>
      </div>

      <div class="form mt-3 col-sm-5" data-controller="select2">
        <%= f.label :meals, 'Choose meals for your diet:' %><br/>
        <%= f.collection_select :meal_ids, meals, :id, :name, {}, multiple: true %>
      </div>

      <div>
        <%= f.submit "Save Diet", class: 'btn btn-primary mt-3'%>
      </div>

  <% end %>
</div>

app/views/diets/edit.html.erb
<%= render 'form', meals: @meals %>

<div class="mt-4">
    <%= link_to 'Cancel', diet_path(@diet), class: 'link-success' %>
</div>

app/views/diets/index.html.erb
<div class="container">
  <h1 class="mb-4 mt-4">Your diet today</h1>
  <div class="mt-3 mb-3">
    <%= form_tag(diets_path, method: :get) do  %>
      <label>Select by day:</label>
      <%= date_field_tag(:search_by_day, params[:search_by_day],
        data: {
        controller: "flatpickr",
        selected: params[:search_by_day]
        }) %>
      <%= submit_tag('Find') %>
    <% end %>
  </div>

  <% if @diets.present? %>
    <% @diets.each do |diet| %>
      <%= render diet %>
    <% end %>
  <% else %>
    <%= 'You have no diets for this day.' %>
  <% end %>

  <% if policy(:diet).new? %>
    <div class="button-group mt-3 mb-3">
      <%= link_to 'Create a new diet', new_diet_path(@diet), class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/diets/new.html.erb
<%= render 'form', meals: @meals %>

<div class="mt-4">
  <%= link_to 'Cancel', diets_path, class: 'link-success' %>
</div>

app/views/diets/show.html.erb
<div class="container mt-4">
  <article class="card mb-3">
    <div class="card-body">
      <h1><%= @diet.name %></h1>

      <section class="card-text">
        <time datetime="<%= @diet.format_date %>">
          <small>for date: <%= @diet.format_date %></small>
        </time>
      </section>

      <hr>

      <div class="mt-4">
        <h3><strong>Meals:</strong></h3>
      </div>

      <div class="my-2">
        <%= render @diet.meals %>
      </div>

      <div class="my-3">
        <h3><strong>Total calories:</strong></h3>
        <%= @diet.meals.sum(&:calories) %>

      </div>

      <div class="my-3">
        <h3><strong>Nutrients:</strong></h3>
        <%= content_tag(:ul) do %>
          <% %w[sugar protein fat carbohydrates].collect do |el| %>
            <%= content_tag(:li) do %>
              <%= el.capitalize %>: <%= @diet.meals.sum(&el.to_sym) %>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <div class="btn-group">
        <div class="left-group">
          <% if policy(@diet).edit? %>
            <%= link_to 'Edit', edit_diet_path(@diet), class: 'btn btn-primary mt-2 me-2'%>
          <% end %>

          <% if policy(@diet).destroy? %>
            <%= button_to 'Delete', diet_path(@diet), method: :delete,
            form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'btn btn-danger mt-2 me-2' %>
          <% end %>
        </div>
      </div>
    </div>
  </article>

  <div class="mt-4">
    <%= link_to 'Back', diets_path, class: 'link-success' %>
  </div>

</div>