config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin_role? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :diets, :eaten_products

  resources :eaten_products do
    get 'send_report', on: :member
  end

  namespace :admin do
    resources :users
  end

  root 'pages#index'
end

app/models/eaten_product.rb
class EatenProduct < ApplicationRecord
  include Authorship

  belongs_to :user

  has_many :eaten_product_meals, dependent: :destroy
  has_many :meals, through: :eaten_product_meals

  scope :search_by_day, ->(eaten_at) do
    eaten_products_list = EatenProduct.find_by(eaten_at: eaten_at || Date.today)
    where(id: eaten_products_list)
  end

  scope :search_by_range, ->(start_date, end_date) do
    EatenProduct.where(eaten_at: start_date..end_date)
  end

  def format_date
    eaten_at.strftime('%d-%m-%Y')
  end
end

app/controllers/eaten_products_controller.rb
class EatenProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_eaten_product, only: %i[show edit update destroy send_report]
  before_action :fetch_meals, only: %i[new edit update]
  before_action :authorize_eaten_product!
  after_action :verify_authorized

  def index
    @eaten_products = current_user.eaten_products.search_by_day(params[:search_by_day]).includes(:user)
    if params[:start_day].present? && params[:end_day].present?
      @eaten_products = current_user.eaten_products.search_by_range(params[:start_day], params[:end_day])
                                    .includes(:user)
    end
  end

  def show; end

  def new
    @eaten_product = current_user.eaten_products.new
  end

  def create
    @eaten_product = current_user.eaten_products.build(create_eaten_product_params)
    if @eaten_product.save
      flash[:success] = 'Eaten meals list was successfully added!'
      redirect_to eaten_product_path(@eaten_product)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @eaten_product.update(update_eaten_product_params)
      flash[:success] = 'Eaten meals list was successfully updated!'
      redirect_to eaten_product_path(@eaten_product)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @eaten_product.destroy
    flash[:success] = 'Eaten meals list was successfully deleted!'

    redirect_to eaten_products_path
  end

  def send_report
    ReportJob.perform_later(@eaten_product, current_user)

    flash[:success] = 'Email with report was successfully sent!'

    redirect_to eaten_products_path
  end

  private

  def create_eaten_product_params
    params.require(:eaten_product).permit(:eaten_at, :search_by_day, :start_day, :end_day, meal_ids: [])
          .merge(user: current_user)
  end

  def update_eaten_product_params
    params.require(:eaten_product).permit(:eaten_at, :search_by_day, :start_day, :end_day, meal_ids: [])
  end

  def find_eaten_product
    @eaten_product = current_user.eaten_products.find(params[:id])
  end

  def fetch_meals
    @meals = Meal.all
  end

  def authorize_eaten_product!
    authorize(@eaten_product || EatenProduct)
  end
end

app/helpers/eaten_products_helper.rb
module EatenProductsHelper
  include TotalStatsHelper
end

app/views/eaten_products/_eaten_product.html.erb
<article class="card mb-3">
    <div class="card-body">
      <h3><%= 'Eaten meals' %></h3>

      <section class="card-text">
        <time datetime="<%= eaten_product.format_date %>">
          <small>for date: <%= eaten_product.format_date %></small>
        </time>
      </section>

      <div class="mt-3 mb-3">
        <%= render eaten_product.meals %>
      </div>

      <div class="btn-group">
        <div class="left-group">
          <%= link_to 'Show', eaten_product_path(eaten_product), class: 'btn btn-primary mt-2 me-2'%>

          <% if policy(eaten_product).edit? %>
            <%= link_to 'Edit', edit_eaten_product_path(eaten_product), class: 'btn btn-primary mt-2 me-2'%>
          <% end %>

          <% if policy(eaten_product).destroy? %>
            <%= button_to 'Delete', eaten_product_path(eaten_product), method: :delete,
            form: { data: { turbo_confirm: 'Are you sure you want to delete this list? All data will be lost.' } },
            class: 'btn btn-danger mt-2 me-2' %>
          <% end %>
        </div>

        <div class="right-group">
          <%= link_to 'Send stats per email', send_report_eaten_product_path(eaten_product), class: 'btn btn-primary mt-2 me-2'%>
        </div>
      </div>
    </div>
</article>

app/views/eaten_products/_form.html.erb
<%= render 'shared/errors', object: @eaten_product %>

<div class="container mt-4">

  <h2>Add new eaten meals list</h2>

  <%= form_with model: @eaten_product do |f| %>

      <div class="field mt-3 col-sm-5">
        <%= f.label :eaten_at, 'You ate it at:' %>
        <%= f.text_field :eaten_at, required: true,
          data: {
          controller: "flatpickr",
          min_date: Time.now
        } %>
      </div>

      <div class="form mt-3 col-sm-5" data-controller="select2">
        <%= f.label :meals, 'Choose meal that you ate:' %><br/>
        <%= f.collection_select :meal_ids, meals, :id, :name, {}, multiple: true %>
      </div>

      <div>
        <%= f.submit "Save", class: 'btn btn-primary mt-3'%>
      </div>
  <% end %>
</div>

app/views/eaten_products/_table.html.erb
<%= content_tag(:table, class: 'table table-striped')  do%>
  <%= content_tag(:thead) do %>
    <%= content_tag(:tr) do %>
      <% ['nutrients', 'in total'].each do |el| %>
        <%= content_tag(:th, scope: "col") do %>
          <%= el.capitalize %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>

  <%= content_tag(:tbody) do %>
    <% %w[calories sugar protein fat carbohydrates].each do |el| %>
      <%= content_tag(:tr) do %>
        <%= content_tag(:th, scope: "row") do %>
          <%= el.capitalize %>
            <%= content_tag(:td) do %>
              <%= object.meals.sum(&el.to_sym) %>
            <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/eaten_products/_total_stats_table.html.erb
<% stats = total_stats(%w[calories sugar protein fat carbohydrates], object) %>

<%= content_tag(:table, class: 'table table-striped')  do%>
  <%= content_tag(:thead) do %>
    <%= content_tag(:tr) do %>
      <% ['nutrients', 'in total'].each do |el| %>
        <%= content_tag(:th, scope: "col") do %>
          <%= el.capitalize %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>

  <%= content_tag(:tbody) do %>
    <% %w[calories sugar protein fat carbohydrates].each do |el| %>
      <%= content_tag(:tr) do %>
        <%= content_tag(:th, scope: "row") do %>
          <%= el.capitalize %>
            <%= content_tag(:td) do %>
              <%= stats[el] %>
            <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/eaten_products/edit.html.erb
<%= render 'form', meals: @meals %>

<div class="mt-4">
  <%= link_to 'Cancel', eaten_product_path(@eaten_product), class: 'link-success' %>
</div>

app/views/eaten_products/index.html.erb
<div class="container">
  <h1 class="mb-4 mt-4">Your eaten meals:</h1>
  <div class="mt-3 mb-3">
    <div>
      <%= form_tag(eaten_products_path, method: :get) do  %>
        <label>Select by day:</label>
        <%= date_field_tag(:search_by_day, params[:search_by_day],
          data: {
          controller: "flatpickr",
          selected: params[:search_by_day]
          }) %>
        <%= submit_tag('Find') %>
      <% end %>
    </div>

    <div class="mt-3">
      <%= form_tag(eaten_products_path, method: :get) do  %>
        <label>Select by day range:</label>
        <%= date_field_tag(:start_day, :start_day,
          data: {
          controller: "flatpickr",
          selected: :start_day
          }) %>
        <%= date_field_tag(:end_day, :end_day,
          data: {
          controller: "flatpickr",
          selected: :end_day
          }) %>
        <%= submit_tag('Find') %>
      <% end %>
    </div>
  </div>

  <% if @eaten_products.present? && params[:start_day].nil? && params[:end_day].nil? %>
    <% @eaten_products.each do |eaten_product| %>
      <%= render eaten_product %>
    <% end %>

    <article class="card mb-3">
      <div class="card-body">
        <h2>Stats for this day:</h2>
        <% @eaten_products.each do |eaten_product| %>
          <%= render 'table', object: eaten_product %>
        <% end %>
      </div>
    </article>

  <% elsif @eaten_products.present? && params[:start_day].present? && params[:end_day].present? %>
    <article class="card mb-3">
      <div class="card-body">
        <h2>
          Stats from <%= Date.parse(params[:start_day]).strftime('%d-%m-%Y') %>
          to <%= Date.parse(params[:end_day]).strftime('%d-%m-%Y') %>:
        </h2>
        <%= render 'total_stats_table', object: @eaten_products %>
      </div>
    </article>

    <% @eaten_products.each do |eaten_product| %>
      <%= render eaten_product %>
    <% end %>

  <% else %>
    <%= 'You have no eaten meals for this day.' %>

    <% if policy(:eaten_product).new? %>
      <div class="button-group mt-3 mb-3">
        <%= link_to 'Add new eaten meals list', new_eaten_product_path(@eaten_product), class: 'btn btn-primary' %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/eaten_products/new.html.erb
<%= render 'form', meals: @meals %>

<div class="mt-4">
  <%= link_to 'Cancel', eaten_products_path, class: 'link-success' %>
</div>

app/views/eaten_products/show.html.erb
<div class="container mt-4">
  <article class="card mb-3">
    <div class="card-body">
      <h1>List of your eaten meals</h1>

      <section class="card-text">
        <time datetime="<%= @eaten_product.format_date %>">
          <small>for date: <%= @eaten_product.format_date %></small>
        </time>
      </section>

      <hr>

      <div class="mt-4">
        <h3><strong>Eaten meals:</strong></h3>
      </div>

      <div class="my-2">
        <%= render @eaten_product.meals %>
      </div>

      <div class="btn-group">
        <div class="left-group">
          <% if policy(@eaten_product).edit? %>
            <%= link_to 'Edit', edit_eaten_product_path(@eaten_product), class: 'btn btn-primary mt-2 me-2'%>
          <% end %>

          <% if policy(@eaten_product).destroy? %>
            <%= button_to 'Delete', eaten_product_path(@eaten_product), method: :delete,
            form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'btn btn-danger mt-2 me-2' %>
          <% end %>
        </div>
      </div>
    </div>
  </article>

  <div class="mt-4">
    <%= link_to 'Back', eaten_products_path, class: 'link-success' %>
  </div>

</div>